apiVersion: v1
kind: Service
metadata:
  name: casino-frontend
  labels:
    app: casino-frontend
spec:
  type: LoadBalancer # Obligatorio para exponer el servicio a Internet
  selector:
    app: casino-frontend # Debe coincidir exactamente con el label del Deployment
  ports:
    - protocol: TCP
      port: 80         # Puerto que recibirá tráfico desde Internet
      targetPort: 8080 # Puerto en el que Nginx está escuchando en el contenedor